apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-rc
  labels:
   app: myapp
   tier: frontend
spec: 
 template:
  metadata:
   name: nginx-container
   labels:
    app: nginx-container
    tier: frontend
    env: dev
  spec:
   containers:
    - name: nginx
      image: nginx 
 replicas: 1     