apiVersion: v1
kind: ReplicationController
metadata:
 name: myapp-rc
 labels: 
  name: myapp-rc
  app: myapp
spec:
 template:
  metadata: 
    name: redis
    labels:
      name: redis
      app: myapp
      type: frontend
  spec:
    containers:
      - name: redis
        image: redis      